apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: kcervenka-ambulance-wl # napr. <pfx>-ambulance-wl
spec:
  title: Zoznam čakajúcich kcervenka # napr. "Zoznam čakajúcich <pfx>"
  description: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Kristián Červenka" # Zadajte mená autorov
  azureLink: "https://kcervenka-ambulance.azurewebsites.net"
  frontendRepoUrl: "https://github.com/K1ko/ambulance-ufe"
  backendRepoUrl: "https://github.com/K1ko/ambulance-webapi"
  gitopsRepoUrl: "https://github.com/K1ko/ambulance-gitops"
